# Generated by Django 5.0.6 on 2025-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(to='blog.post'),
        ),
    ]
