# Generated by Django 5.0.6 on 2025-03-27 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'reference')},
        ),
    ]
